twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        default_agent_image_path: '%assets_default_agent_profile_image_path%'
        default_customer_image_path: '%assets_default_customer_profile_image_path%'
        default_helpdesk_image_path: '%assets_default_helpdesk_profile_image_path%'